// angular-greenborn-sso-front/src/components/sso-callback/sso-callback.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { SSOAuthService } from '../../services/sso-auth.service';
import { SSOCallbackResult } from '../../models/sso.model';

@Component({
  standalone: true,
  imports: [CommonModule],
  selector: 'gb-sso-callback',
  templateUrl: './sso-callback.component.html',
  styleUrls: ['./sso-callback.component.scss'],
})
export class SsoCallbackComponent implements OnInit, OnDestroy {
  @Input() registerPath = '/registro';
  @Input() fallbackPath = '/';
  @Input() autoRedirect = true;

  @Output() success = new EventEmitter<SSOCallbackResult>();
  @Output() error = new EventEmitter<Error>();
  @Output() noParams = new EventEmitter<void>();

  loading = true;
  errorMessage = '';
  result: SSOCallbackResult | null = null;
  private sub: Subscription | null = null;

  constructor(
    private router: Router,
    private route: ActivatedRoute,
    private ssoAuth: SSOAuthService
  ) {}

  ngOnInit(): void {
    this.sub = this.route.queryParams.subscribe((params) => {
      const token = params['token'];
      const uniqueId = params['unique_id'];

      if (token && uniqueId) {
        this.handleCallback(token, uniqueId);
      } else {
        this.loading = false;
        this.errorMessage = 'Parámetros de autenticación no recibidos.';
        this.noParams.emit();
        if (this.autoRedirect) {
          setTimeout(() => this.router.navigateByUrl(`/login?error=missing_params`), 3000);
        }
      }
    });
  }

  private handleCallback(token: string, uniqueId: string): void {
    this.ssoAuth
      .handleCallback(token, uniqueId)
      .then((result) => {
        this.loading = false;
        this.result = result;
        this.success.emit(result);
        if (this.autoRedirect) {
          if (result.exists) {
            const redirectUrl = this.ssoAuth.getAndClearRedirectUrl();
            this.router.navigateByUrl(redirectUrl || this.fallbackPath);
          } else {
            this.router.navigateByUrl(
              `${this.registerPath}?email=${encodeURIComponent(result.ssoEmail)}`
            );
          }
        }
      })
      .catch((err: Error) => {
        this.loading = false;
        this.errorMessage = 'Error al autenticar. Intenta nuevamente.';
        this.error.emit(err);
        if (this.autoRedirect) {
          setTimeout(() => this.router.navigateByUrl('/login?error=auth_failed'), 3000);
        }
      });
  }

  ngOnDestroy(): void {
    if (this.sub) {
      this.sub.unsubscribe();
    }
  }
}

<div class="gb-sso-callback">
  @if (loading) {
    <div class="gb-sso-callback__loading">
      <span class="gb-sso-callback__spinner" role="status"></span>
      <p>Autenticando...</p>
    </div>
  } @else if (errorMessage) {
    <div class="gb-sso-callback__error">
      <p>{{ errorMessage }}</p>
    </div>
  } @else {
    <ng-content></ng-content>
  }
</div>

// vue-greenborn-sso-front/src/components/SsoCallback.vue
<template>
  <div class="vgb-sso-callback">
    <div v-if="loading" class="vgb-sso-callback__loading">Verificando autenticación…</div>
    <div v-else-if="error" class="vgb-sso-callback__error">{{ error }}</div>
    <slot v-else />
  </div>
</template>

<script setup>
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useSsoAuth } from '../composables/useSsoAuth.js'

const props = defineProps({
  registerPath: {
    type: String,
    default: '/registro',
  },
  fallbackPath: {
    type: String,
    default: '/',
  },
  autoRedirect: {
    type: Boolean,
    default: true,
  },
  config: {
    type: Object,
    default: () => ({}),
  },
})

const emit = defineEmits(['success', 'error', 'no-params'])

const route = useRoute()
const router = useRouter()
const sso = useSsoAuth(props.config)

const loading = ref(true)
const error = ref('')

onMounted(async () => {
  const token = route.query.token
  const uniqueId = route.query.unique_id

  if (!token || !uniqueId) {
    error.value = 'Parámetros de autenticación no recibidos.'
    emit('no-params')
    if (props.autoRedirect) {
      setTimeout(() => router.push({ path: '/login', query: { error: 'missing_params' } }), 3000)
    }
    loading.value = false
    return
  }

  try {
    const result = await sso.handleCallback(token, uniqueId)
    emit('success', result)
    loading.value = false
    if (props.autoRedirect) {
      if (result.exists) {
        const redirectUrl = sso.getAndClearRedirectUrl()
        router.push(redirectUrl || props.fallbackPath)
      } else {
        router.push({
          path: props.registerPath,
          query: { email: encodeURIComponent(result.ssoEmail || '') },
        })
      }
    }
  } catch (err) {
    console.error('Error en callback SSO:', err)
    error.value = 'Error al autenticar. Intenta nuevamente.'
    emit('error', err)
    loading.value = false
    if (props.autoRedirect) {
      setTimeout(() => router.push({ path: '/login', query: { error: 'auth_failed' } }), 3000)
    }
  }
})
</script>

<style>
.vgb-sso-callback {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
  padding: 1rem;
  font-family: system-ui, -apple-system, sans-serif;
}
.vgb-sso-callback__loading {
  color: #666;
}
.vgb-sso-callback__error {
  color: #b00020;
  text-align: center;
}
</style>
